/* Shell variables */
#define MENDER_BOOT_PART_NUMBER 0
#define MENDER_ROOTFS_PART_A_NUMBER 6
#define MENDER_ROOTFS_PART_B_NUMBER 7
#define MENDER_UBOOT_STORAGE_INTERFACE "mmc"
#define MENDER_UBOOT_STORAGE_DEVICE 0

/* BB variables. */
#define MENDER_STORAGE_DEVICE_BASE "/dev/mmcblk0p"
#define MENDER_UBOOT_ENV_STORAGE_DEVICE_OFFSET_1 (3 * 1024 * 1024)
#define MENDER_UBOOT_ENV_STORAGE_DEVICE_OFFSET_2 (6 * 1024 * 1024)

/* For sanity checks. */
#define MENDER_BOOTENV_SIZE (64*1024)
